name: order

on: workflow_dispatch

jobs:
  order:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Extract order details
        id: extract_details
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=3
          ISSUE_BODY=$(GH_TOKEN=${{ secrets.GITHUB_TOKEN }} gh issue view $ISSUE_NUMBER --json body --jq .body)
          echo "$ISSUE_BODY"
