name: order

on: workflow_dispatch

jobs:
  order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get issue details
        id: get_issue
        run: |
          ISSUE_NUMBER=6
          ISSUE_TITLE=$(gh issue view $ISSUE_NUMBER --json title --jq .title)
          ISSUE_BODY=$(gh issue view $ISSUE_NUMBER --json body --jq .body)
          ISSUE_AUTHOR=$(gh issue view $ISSUE_NUMBER --json author --jq .author.login)
          
          if [[ ! $ISSUE_TITLE =~ ^Order ]]; then
            echo "ISSUE_TITLE 不以 Order 开头，终止程序"
            exit 1
          fi

          FIRST_LINE=$(echo $ISSUE_BODY | head -n 1)
          echo "md5: $FIRST_LINE"
          REMAINING_BODY=$(echo $ISSUE_BODY | tail -n +2)
          echo "md5: $FIRST_LINE"
          echo "$REMAINING_BODY"

          MD5_REMAINING_BODY=$(echo -n $REMAINING_BODY | md5sum | awk '{ print $1 }')
          echo "md5: $MD5_REMAINING_BODY"
          if [[ "$MD5_REMAINING_BODY" != $FIRST_LINE ]]; then
            echo "MD5 校验失败，终止程序"
            exit 1
          fi

          ENCRYPTED_INFO=$(echo $REMAINING_BODY | sed -n '/### Information(Encrypted)/,$p' | sed '1d')
          IFS=$'\n' read -r -d '' -a ENCRYPTED_ARRAY <<< "$ENCRYPTED_INFO"
          for line in "${ENCRYPTED_ARRAY[@]}"; do
            echo "$line"
          done

   
