name: order

on: workflow_dispatch

jobs:
  order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get issue details
        id: get_issue
        env:
          PRI_KEY: ${{ secrets.ORDER_PRI_KEY }}
        run: |
          ISSUE_NUMBER=6
          ISSUE_TITLE=$(gh issue view $ISSUE_NUMBER --json title --jq .title)
          ISSUE_BODY=$(gh issue view $ISSUE_NUMBER --json body --jq .body)
          ISSUE_AUTHOR=$(gh issue view $ISSUE_NUMBER --json author --jq .author.login)
          
          if [[ ! $ISSUE_TITLE =~ ^Order ]]; then
            echo "ISSUE_TITLE 不以 Order 开头，终止程序"
            exit 1
          fi
          
          # 创建一个临时文件来存储私钥
          echo "$PRI_KEY" > private_key.pem

          # 初始化变量
          MD=""
          VALUE=""
          is_info_section=false

          while IFS= read -r line; do
            if [[ -z $MD ]]; then
              MD="$line"
            elif [[ $line =~ "Information" ]]; then
              is_info_section=true
            elif $is_info_section; then
              echo "$line"
              decrypted_line=$(echo "$line" | base64 -d | openssl pkeyutl -decrypt -inkey private_key.pem -pkeyopt rsa_padding_mode:pkcs1)
              VALUE+="$decrypted_line"
            fi
          done <<< "$ISSUE_BODY"

          echo "MD: $MD"
          echo "VALUE: $VALUE"

          rm private_key.pem

   