name: order

on: workflow_dispatch

jobs:
  order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Extract order details
        id: extract_details
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRI_KEY: ${{ secrets.ORDER_PRI_KEY }}
        run: |
          echo $PRI_KEY
          ISSUE_NUMBER=3
          ISSUE_BODY=$(gh issue view $ISSUE_NUMBER --json body --jq .body)
          echo "$ISSUE_BODY"

          # 提取Information(Encrypted)下的内容
          INFO_ENCRYPTED=$(echo "$ISSUE_BODY" | awk '/### Information\(Encrypted\)/{flag=1;next}/```/{flag=0}flag')
          echo "$INFO_ENCRYPTED"

          # 按 \n 分组
          IFS=$'\n' read -rd '' -a lines <<<"$INFO_ENCRYPTED"
          for line in "${lines[@]}"; do
            echo "$line"
          done