name: order

on: workflow_dispatch

jobs:
  order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Get issue details
        id: get_issue
        env:
          PRI_KEY: ${{ secrets.ORDER_PRI_KEY }}
        run: |
          ISSUE_NUMBER=7
          ISSUE_TITLE=$(gh issue view $ISSUE_NUMBER --json title --jq .title)
          ISSUE_BODY=$(gh issue view $ISSUE_NUMBER --json body --jq .body)
          ISSUE_AUTHOR=$(gh issue view $ISSUE_NUMBER --json author --jq .author.login)
          
          if [[ ! $ISSUE_TITLE =~ ^[Oo]rder ]]; then
            echo "this issue is not an order issue"
            exit 0
          fi
          
          FIRST_LINE=$(echo "$ISSUE_BODY" | head -n 1 | tr -d '\n\r')
          REMAINING_BODY=$(echo "$ISSUE_BODY" | tail -n +2 | tr -d '\n\r')
          MD5=$(echo -n $REMAINING_BODY | md5sum | awk '{ print $1 }')
          
          if [[ "$MD5" != "$FIRST_LINE" ]]; then
            echo "md5 incorrect"
            gh issue comment $ISSUE_NUMBER --body "md5 incorrect,closed this issue."
            gh issue close $ISSUE_NUMBER
            exit 0
          fi
          
          # 创建一个临时文件来存储私钥
          echo "$PRI_KEY" > private_key.pem

          # 初始化变量
          
          VALUE=""
          is_info_section=false

          while IFS= read -r line; do
            if [[ $line =~ "Information(Encrypted)" ]]; then
              is_info_section=true
            elif $is_info_section; then
              decrypted_line=$(echo "$line" | tr -d '\n\r' | base64 -d | openssl pkeyutl -decrypt -inkey private_key.pem -pkeyopt rsa_padding_mode:pkcs1)
              VALUE+="$decrypted_line"
            fi
          done <<< "$ISSUE_BODY"

          echo "VALUE: $VALUE"
          rm private_key.pem

          gh issue comment $ISSUE_NUMBER --body "## Please click on the link to make payment\nhttps://github.com/gitvzz/shopping?id=$MD5"
