name: order

on: workflow_dispatch

jobs:
  order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get issue details
        id: get_issue
        run: |
          ISSUE_NUMBER=3
          ISSUE_DETAILS=$(gh issue view $ISSUE_NUMBER --json title,body,author,state,createdAt,updatedAt --jq '{title: .title, body: .body, author: .author.login, state: .state, createdAt: .createdAt, updatedAt: .updatedAt}')
          echo "Issue Details: $ISSUE_DETAILS"
          echo "issue_details=$ISSUE_DETAILS" >> $GITHUB_ENV

      - name: Display issue details
        run: |
          echo "Issue Details: ${{ env.issue_details }}"